[package]
name = "tormov"
version = "0.1.1"
authors = ["Francesco Cogno <francesco.cogno@outlook.com>"]

[dependencies]
regex        = "0.2.2"
serde        = "1.0.14"
serde_json   = "1.0.3"
serde_derive = "1.0.14"
